# Generated by Django 4.0.3 on 2022-04-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='ListingLocation',
        ),
    ]
