# Generated by Django 4.0.3 on 2022-04-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
