# Generated by Django 4.0.4 on 2022-04-12 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing', to='api.listinglocation'),
        ),
    ]
