# Generated by Django 4.0.4 on 2022-04-22 07:41

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='thumbnail_large',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='api/images/thumbnails'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
