# Generated by Django 4.0.4 on 2022-04-22 11:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_listingimage_thumbnail_large_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='thumbnail_large',
            new_name='thumbnail_lg',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='thumbnail_sm',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='api/images/thumbnails'),
        ),
    ]
