# Generated by Django 4.0.4 on 2022-04-22 11:12

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_thumbnail_large_listingimage_thumbnail_lg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='thumbnail_lg',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='api/images/thumbnails/large'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='thumbnail_sm',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='api/images/thumbnails/small'),
        ),
    ]
