# Generated by Django 4.0.4 on 2022-04-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_listingimage_thumbnail_lg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='thumbnail_sm',
            new_name='thumbnail_card',
        ),
        migrations.RenameField(
            model_name='listingimage',
            old_name='thumbnail_lg',
            new_name='thumbnail_detail',
        ),
    ]
