# Generated by Django 4.0.4 on 2022-05-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expoPushToken',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
