# Generated by Django 4.0.4 on 2022-05-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_message_sentonmessage_messagefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='fromUser',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='toUser',
            new_name='to_user',
        ),
    ]
