# Generated by Django 4.0.4 on 2022-05-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0026_rename_fromuser_message_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='used_for_reply_message',
        ),
        migrations.AddField(
            model_name='message',
            name='used_for_reply_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='message',
            name='used_for_reply_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
