# Generated by Django 4.0.4 on 2022-05-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_message_used_for_reply_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='used_for_reply_content_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='used_for_reply_object_id',
        ),
        migrations.AddField(
            model_name='message',
            name='attached_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_messages', to='api.listing'),
        ),
        migrations.AddField(
            model_name='message',
            name='used_for_reply_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replied_messages', to='api.message'),
        ),
    ]
