# Generated by Django 4.0.4 on 2022-05-17 14:22

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_message_used_for_reply_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefile',
            name='file',
            field=models.FileField(upload_to='api/messageFiles', validators=[api.validators.validate_file_size]),
        ),
    ]
