# Generated by Django 4.0.4 on 2022-05-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_chat_sent_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
