# Generated by Django 4.0.4 on 2022-05-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_delete_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentonmessage',
            options={'ordering': ['message__sent_at']},
        ),
    ]
